FROM python:3.7-alpine
LABEL maintainer="Ilya Radostev <feeltheajf@gmail.com>"

RUN apk add --no-cache git

WORKDIR /trufflehog3
ADD . /trufflehog3
RUN pip install .

ENTRYPOINT [ "trufflehog3", "/source" ]
CMD [ "--help" ]
