#!/bin/bash
set -e

WD=$(realpath ${1:?})
REPO="${WD}/repo"
META="${WD}/meta.yaml"

HIGH_ENTROPY_STRING="4b2810c1a65d47af13dc8d6eae8d36"
PRIVATE_KEY_STRING="-----BEGIN RSA PRIVATE KEY-----"

function log {
    echo "[I] $*"
}

function err {
    echo "[E] $*"
}

function cleanup {
    err "unexpected error. cleaning up"
    rm -rf "${REPO}"
    exit 1
}

trap cleanup ERR

log "changing working directory"
mkdir -p "$REPO" && cd "$REPO"

log "initializing repository"
git init
echo "# Test Repo" > README.md
git add . && git commit -m "initial commit"

log "committing High entropy"
echo "$HIGH_ENTROPY_STRING" > high_entropy.txt
git add . && git commit -m "High entropy"
high_entropy_commit=$(git rev-parse HEAD)

log "making some dumb commits"
for i in $(seq 1 5); do
    echo "$i" > "file${i}.py"
    echo "$i" >> README.md
    git add . && git commit -m "commit $i"
done

log "committing RSA private key"
echo "$PRIVATE_KEY_STRING" > private.key
git add . && git commit -m "RSA private key"
private_key_commit=$(git rev-parse HEAD)


log "making some dumb commits"
for i in $(seq 6 10); do
    echo "$i" > "file${i}.py"
    echo "$i" >> README.md
    git add . && git commit -m "commit $i"
done

log "removing RSA private key"
git rm private.key
git add . && git commit -m "RSA private key"

echo "
high_entropy_commit: $high_entropy_commit
private_key_commit: $private_key_commit
" > "$META"
